### ISSUE TITLE
Compatibility with base 4.9

### ISSUE THREAD

**Issue by HalosGhost** [jeffreyrosenbluth/lucid-svg#10]
Now that ghc 8.0 has dropped with the new base package, I find myself in a situation where lucid-svg claims to not be compatible, and so I can no longer build my package. I am aware that I could just downgrade ghc/cabal, but since lucid is not affected by any compatibility issues (it claims to be compatible with base<5), I was wondering if this might be a simple fix by just changing the `.cabal` file to relax the constraint.

**Comment by jeffreyrosenbluth** [comment]
Fixed in 0.7
thanks
