### ISSUE TITLE
title and desc elements take [Attribute] but no Text

### ISSUE THREAD

**Issue by HalosGhost** [jeffreyrosenbluth/lucid-svg#8]
In all example SVGs I have seen, I have seen `<title>` and `<desc>` used like so (or very similarly):

``` svg
<svg…
    <symbol…
        <title>What this thing is called</title>
        <desc>A short description of what it is</desc>
        …
    </symbol>
</svg>
```

(cf. [the MDN SVG reference](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title))

However, `title_` and `desc_` only take a `[Attribute]` and no `Text` argument. So, I can clearly add attributes to the elements, but I cannot add the text inside. Was this intentional? If so, what was the motivation? If not, would a PR be accepted to allow for this?

**Comment by jeffreyrosenbluth** [comment]
If gladly accept a pr

**Comment by HalosGhost** [comment]
@jeffreyrosenbluth, awesome! I will see if I cannot get that done this weekend!

**Comment by HalosGhost** [comment]
All right, I'd like to get this done today, but I have an implementation question. Both `title` and `desc` have HTML-style close-tags and should only contain text. However, there is no function in Lucid.Base that does this (so far as I know). The choice is between having a full set of children or having no children.

So, my question is: should I implement a function specifically for this text-only case to ensure that only text is passed to `title` and `desc`, or should I simply define them as having children and let the user generate possibly-invalid code? (I'm leaning towards the former, but I wanted to check which you would prefer)

**Comment by jeffreyrosenbluth** [comment]
I think the later. Many tags have restrictions on the types of children.
I'm in my mobile right now so I can't look at the code until later. Thx.

**Comment by HalosGhost** [comment]
@jeffreyrosenbluth, thanks for the great library and for being open to PRs! I look forward to the release with this fix included!
